classdef ORBDetector < localFeatures.CVDetector
    %ORBDETECTOR Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        Opts = struct(...
                'NFeatures', 500, ...            
                'ScaleFactor', 1.2, ...
                'NLevels', 8, ...
                'EdgeThreshold', 31, ...
                'WTA_K', 2, ...
                'PatchSize', 31 ...
        );
    end
    
    methods
        
        function obj = ORBDetector(varargin)
            obj = obj@localFeatures.CVDetector('ORB',varargin);
        end
        
        function [features, descriptors] = extract(obj, imagePath)
            if strfind(imagePath, '.jxr')
                img = convert.Converter.readJXR(imagePath);
            else
                img = imread(imagePath);
            end
            import cv.*
            [features, descriptors] = ORB(rgb2gray(img),... 
                'NFeatures',  obj.Opts.NFeatures, ...            
                'ScaleFactor', obj.Opts.ScaleFactor, ...
                'NLevels', obj.Opts.NLevels, ...
                'EdgeThreshold', obj.Opts.EdgeThreshold, ...
                'WTA_K', obj.Opts.WTA_K, ...
                'PatchSize', obj.Opts.PatchSize ...
            );
        end
    end
    
end

